name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CMAKE_GENERATOR: Ninja
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-22.04
            build_type: Release
            cmake_flags: ""

          - name: macOS
            os: macos-13
            build_type: Release
            cmake_flags: ""

          - name: Windows
            os: windows-latest
            build_type: Release
            cmake_flags: ""

          - name: Coverage
            os: ubuntu-22.04
            build_type: Debug
            cmake_flags: '-D CMAKE_CXX_FLAGS="--coverage"'

          - name: Sanitize
            os: ubuntu-22.04
            build_type: Debug
            cmake_flags: '-D CMAKE_CXX_FLAGS="-g -fno-omit-frame-pointer -fsanitize=address,undefined -fno-sanitize-recover=all"'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: >
          sudo apt update &&
          sudo apt install
          libcurl4-openssl-dev
          libasound2-dev
          libx11-dev
          libxinerama-dev
          libxext-dev
          libfreetype6-dev
          libwebkit2gtk-4.0-dev
          libglu1-mesa-dev
          xvfb
          ninja-build
          gcovr

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install ninja

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: choco install ninja ccache

      - name: Install conan
        run: |
          pip3 install --upgrade conan
          conan profile detect -f

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: neo-juce-test-${{ matrix.name }}

      - name: CMake configure
        if: runner.os != 'Windows'
        shell: bash
        run: >
          cmake
          -S .
          -B build
          -G Ninja
          -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -D CMAKE_UNITY_BUILD=ON
          -D CMAKE_PROJECT_TOP_LEVEL_INCLUDES="external/cmake-conan/conan_provider.cmake"
          ${{ matrix.cmake_flags }}

      - name: CMake configure
        if: runner.os == 'Windows'
        shell: bash
        run: >
          cmake
          -S .
          -B build
          -G "Visual Studio 17 2022"
          -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -D CMAKE_UNITY_BUILD=ON
          -D CMAKE_PROJECT_TOP_LEVEL_INCLUDES="external/cmake-conan/conan_provider.cmake"
          ${{ matrix.cmake_flags }}

      - name: CMake build
        shell: bash
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: CTest
        shell: bash
        run: ctest --test-dir build -C ${{ matrix.build_type }} --output-on-failure

      - name: Coverage report
        if: contains(matrix.name, 'Coverage')
        shell: bash
        run: >
          gcovr
          --xml-pretty
          -e ".*_test\.cpp"
          --exclude-unreachable-branches
          --exclude-throw-branches
          -r modules
          -s build
          -o build/coverage.xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        if: contains(matrix.name, 'Coverage')
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/coverage.xml
          fail_ci_if_error: true
